set_property PACKAGE_PIN V10 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports yout]
set_property IOSTANDARD LVCMOS18 [get_ports yout]
set_property IOSTANDARD LVCMOS18 [get_ports {ain[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ain[0]}]
set_property PACKAGE_PIN L16 [get_ports {ain[1]}]
set_property PACKAGE_PIN J15 [get_ports {ain[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]