set_property PACKAGE_PIN V10 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports ain]
set_property PACKAGE_PIN L16 [get_ports reset]
set_property PACKAGE_PIN J13 [get_ports yout]
set_property IOSTANDARD LVCMOS18 [get_ports ain]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports yout]
set_property IOSTANDARD LVCMOS18 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {count[0]}]
set_property PACKAGE_PIN V12 [get_ports {count[3]}]
set_property PACKAGE_PIN V14 [get_ports {count[2]}]
set_property PACKAGE_PIN V15 [get_ports {count[1]}]
set_property PACKAGE_PIN T16 [get_ports {count[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

