set_property PACKAGE_PIN N14 [get_ports {count_out[3]}]
set_property PACKAGE_PIN J13 [get_ports {count_out[2]}]
set_property PACKAGE_PIN K15 [get_ports {count_out[1]}]
set_property PACKAGE_PIN H17 [get_ports {count_out[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN V10 [get_ports direction]
set_property IOSTANDARD LVCMOS18 [get_ports {count_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {count_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {count_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {count_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports direction]

set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg_Out[0]}]
set_property PACKAGE_PIN T10 [get_ports {Seg_Out[0]}]
set_property PACKAGE_PIN R10 [get_ports {Seg_Out[1]}]
set_property PACKAGE_PIN K16 [get_ports {Seg_Out[2]}]
set_property PACKAGE_PIN K13 [get_ports {Seg_Out[3]}]
set_property PACKAGE_PIN P15 [get_ports {Seg_Out[4]}]
set_property PACKAGE_PIN T11 [get_ports {Seg_Out[5]}]
set_property PACKAGE_PIN L18 [get_ports {Seg_Out[6]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
